
import type { Story, UserPost, PostComment, UserProfile } from '@/types';

export const mockUsers: UserProfile[] = [
  {
    id: 'user123', // StorySeeker92
    name: 'Katha Seeker',
    username: 'StorySeeker92',
    email: 'story.seeker@example.com',
    avatarUrl: 'https://placehold.co/150x150/B4317B/F7F2FA?text=SS',
    bio: "Avid reader and aspiring author. Always on the lookout for the next great adventure within the pages of a book. Favorite genres: Sci-Fi and Fantasy. Now sharing my thoughts here too!",
    readingHistory: [
      { storyId: '1', title: 'The Whispers of Chronos', lastReadChapterId: 'c3', progress: 75 },
      { storyId: '2', title: 'Beneath the Emerald Canopy', lastReadChapterId: 'c1', progress: 20 },
    ],
    favorites: ['1'],
    submittedStories: [],
    followers: 1250,
    following: 180,
  },
  {
    id: 'user001',
    name: 'Riley Reader',
    username: 'ReaderRiley',
    email: 'riley@example.com',
    avatarUrl: 'https://placehold.co/100x100/8E7CC3/FFFFFF?text=RR',
    bio: 'Loves fantasy and sci-fi. Always looking for new authors.',
    followers: 150,
    following: 75,
    readingHistory: [],
    favorites: [],
    submittedStories: [],
  },
  {
    id: 'user002',
    name: 'Alex Author',
    username: 'AuthorAlex',
    email: 'alex@example.com',
    avatarUrl: 'https://placehold.co/100x100/E8A87C/FFFFFF?text=AA',
    bio: 'Aspiring novelist. Currently working on a steampunk adventure.',
    followers: 320,
    following: 120,
    readingHistory: [],
    favorites: [],
    submittedStories: [],
  },
  {
    id: 'author1',
    name: 'Eleanor Vance',
    username: 'EleanorVanceAuthor', // Made username more distinct
    email: 'eleanor@example.com',
    avatarUrl: 'https://placehold.co/100x100/B4317B/FFFFFF?text=EV',
    bio: 'Author of "The Whispers of Chronos". Fascinated by time and its mysteries.',
    followers: 5000,
    following: 10,
    readingHistory: [],
    favorites: [],
    submittedStories: [{storyId: '1', title: 'The Whispers of Chronos'}],
  },
   {
    id: 'author2',
    name: 'Marcus Stone',
    username: 'MarcusStoneWrites',
    email: 'marcus.stone@example.com',
    avatarUrl: 'https://placehold.co/100x100/5DADE2/FFFFFF?text=MS',
    bio: 'Explorer of fantastical worlds and chronicler of their tales.',
    followers: 3200,
    following: 25,
    readingHistory: [],
    favorites: [],
    submittedStories: [{storyId: '2', title: 'Beneath the Emerald Canopy'}],
  },
  {
    id: 'userBot1',
    name: 'Book Fanatic',
    username: 'BookFanatic',
    email: 'bf@example.com',
    avatarUrl: 'https://placehold.co/40x40/7E3AF2/FFFFFF?text=BF',
    bio: 'Just here for the stories!',
    followers: 50,
    following: 100,
    readingHistory: [],
    favorites: [],
    submittedStories: [],
  },
  {
    id: 'userBot2',
    name: 'Page Explorer',
    username: 'PageExplorer',
    email: 'pe@example.com',
    avatarUrl: 'https://placehold.co/40x40/F28A3A/FFFFFF?text=PE',
    bio: 'Exploring one page at a time.',
    followers: 75,
    following: 90,
    readingHistory: [],
    favorites: [],
    submittedStories: [],
  },
];


export const mockStories: Story[] = [
  {
    id: '1',
    title: 'The Whispers of Chronos',
    author: 'Eleanor Vance',
    authorId: 'author1',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Chronos',
    description: 'A thrilling journey through time as a historian uncovers a device that can alter history.',
    tags: ['sci-fi', 'time travel', 'adventure'],
    chapters: [
        { id: 'c1_1', title: 'Chapter 1: The Attic Anomaly', content: 'The old grandfather clock in the attic wasn\'t just telling time; it was leaking it...<br/><br/>Dr. Aris Thorne, a man whose tweed jacket seemed permanently infused with the scent of old parchment and dust, ran a trembling hand through his already disheveled hair. He\'d inherited this sprawling Victorian monstrosity from a great-aunt he\'d never met, a woman known in local lore as "Mad Elara." The clock, a towering monolith of dark oak and tarnished brass, was her most infamous possession. Locals whispered it chimed at hours that didn’t exist.<br/><br/>Today, it was doing more than chiming. A faint, iridescent mist, smelling of ozone and something ancient, like petrified wood, was seeping from the seams around its glass face. The pendulum, usually a steadfast metronome, swung erratically, sometimes impossibly fast, sometimes slow enough to suggest time itself was struggling to keep pace.<br/><br/>"This is... unexpected," Aris muttered, his voice a dry croak. His academic curiosity warred with a primal instinct to flee. Curiosity, as it often did, won. He approached cautiously, his antique spectacles slipping down his nose. The air around the clock shimmered, distorting the familiar clutter of the attic – cobweb-laden trunks, stacks of forgotten portraits, a dressmaker\'s dummy draped in a moth-eaten shawl.<br/><br/>As he reached out, a wave of vertigo washed over him. The mist thickened, swirling, and the rhythmic tick-tock of the clock dissolved into a cacophony of overlapping chimes, whispers, and the distant roar of… was that traffic? Impossible. The house was miles from any main road.<br/><br/>The floor beneath him seemed to lurch. He stumbled, his hand brushing against the clock\'s cold casing. The world dissolved into a kaleidoscope of light and shadow. He felt a sensation of falling, not downwards, but… inwards. Sideways. Every-which-ways.<br/><br/>Then, silence. And a hard landing.', order: 1 },
        { id: 'c1_2', title: 'Chapter 2: Echoes of Tomorrow', content: 'His first jump was unintentional, a chaotic tumble into a future he barely recognized...<br/><br/>Aris coughed, dust and the metallic tang of unfamiliar air filling his lungs. He was sprawled on a cold, smooth surface that hummed faintly beneath him. Gone were the cobwebs and wooden beams of the attic. Instead, sleek, luminescent panels curved overhead, casting a soft, blue-white glow. The air was sterile, filtered, and carried the scent of synthesized polymers.<br/><br/>He pushed himself up, groaning. His tweed jacket felt ridiculously out of place. Towering structures of glass and chrome pierced a sky that wasn\'t quite the right shade of blue – it was too clear, too… managed. Vehicles, silent and aerodynamic, zipped along elevated pathways, their forms blurring with speed.<br/><br/>"Good heavens," he breathed, adjusting his spectacles, which had miraculously survived the transit. "Where in blazes am I?"<br/><br/>A sleek, androgynous figure in a silver jumpsuit glided towards him, its movements unnervingly smooth. "Temporal anomaly detected," it intoned, its voice a perfectly modulated, genderless baritone. "Unit 734, please state your origin point and temporal displacement vector."<br/><br/>Aris blinked. "I… I beg your pardon? I was in my attic. In Oakhaven. Nineteen-fifty-two." He glanced around wildly. "This most certainly isn\'t Oakhaven."<br/><br/>The silver figure tilted its head, its optical sensors – large, dark lenses – focusing on him. "Temporal displacement confirmed. Subject designation: \\\'Aris Thorne.\\\' Origin timeline: Mid-20th Century, Standard Earth Calendar. You are currently in Neo-London, year 2342. You have breached Chronos Protocol Section 3, Paragraph 7: Unauthorized Temporal Incursion."<br/><br/>"Chronos Protocol?" Aris stammered. "Twenty-three forty-two? Good lord, the clock… it actually worked!" His initial shock was rapidly being overtaken by a historian\'s exhilaration, and a healthy dose of terror. "I need to get back!"<br/><br/>"Return is not immediately possible," Unit 734 stated flatly. "Your method of transit is… primitive and unstable. You will be escorted to a containment and debriefing facility." Two more silver figures, identical to the first, materialized silently beside it. Aris suddenly felt very small, and very, very far from home.', order: 2 },
        { id: 'c1_3', title: 'Chapter 3: The Chronos Protocol', content: 'The organization known only as "Veridian" had been tracking temporal disturbances...<br/><br/>The "containment facility" was less a prison and more like a very minimalist, very sterile luxury hotel room. Unit 734, or a perfect replica, delivered nutrient paste (which tasted vaguely of synthetic strawberries) and provided Aris with a set of plain, comfortable grey overalls.<br/><br/>Days blurred. He was questioned, scanned, and observed. He learned that "Veridian" was the global authority responsible for maintaining temporal integrity – the Chronos Protocol. His accidental arrival had sent ripples through their meticulously managed timeline. They were, to put it mildly, not pleased.<br/><br/>A stern-faced woman named Director Eva Rostova finally came to see him. Her uniform was a darker shade of silver, and her eyes held the weary authority of someone who had seen too much of time\'s messy potential. "Dr. Thorne," she began, her voice crisp, "your great-aunt Elara was a known rogue chrononaut. Her device, that… clock of yours, is an unregistered, highly dangerous temporal displacement unit. We thought all her toys had been decommissioned."<br/><br/>"Rogue chrononaut?" Aris felt a thrill. Mad Elara indeed. "She never mentioned it in her letters."<br/><br/>"She wouldn\'t have," Rostova said dryly. "What concerns us is how you activated it, and the potential paradoxes you might create simply by existing here. Or by returning incorrectly." She explained that uncontrolled jumps like his could unravel the fabric of reality. Veridian’s own methods were precise, calculated, requiring immense energy and navigating complex temporal currents.<br/><br/>"We can attempt to send you back, Dr. Thorne," Rostova continued, "but it will be risky. We need to calibrate our systems to the unique signature of your clock. And we need to ensure you haven\'t… contaminated this timeline too much."<br/><br/>Aris understood. He was a historical artifact, suddenly alive and kicking in a future that wasn’t prepared for him. And he, a historian, was now a potential threat to history itself. The irony was not lost on him.<br/><br/>"What do you need from me?" he asked, resigned but also intrigued. The adventure, it seemed, was just beginning.', order: 3 },
    ],
    genre: 'Science Fiction',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.8,
    views: 25000,
    isTrending: true,
    isCurated: true,
    category: 'Trending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    dataAihint: "futuristic city"
  },
  {
    id: '2',
    title: 'Beneath the Emerald Canopy',
    author: 'Marcus Stone',
    authorId: 'author2',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Canopy',
    description: 'Explorers venture deep into an uncharted jungle, finding more than just exotic flora and fauna.',
    tags: ['fantasy', 'exploration', 'magic'],
    chapters: [
        { id: 'c2_1', title: 'Chapter 1: The Summons', content: 'The Royal Cartographers Guild had a new assignment... their most daring yet. A faded map, rumored to be a forgery, spoke of Xylos, the Verdant Heart, a jungle said to be untouched by modern hands, teeming with creatures of myth and flora that defied botanical classification. Lord Alistair, a man whose appetite for adventure was matched only by his overflowing coffers, had commissioned the expedition. He wanted Xylos mapped, its secrets unveiled.<br/><br/>Elara Meadowlight, a botanist with an uncanny knack for communicating with plants (a skill often dismissed by her more staid colleagues), and Jax Thornwood, a rugged survivalist whose scars told tales of past expeditions gone awry, were summoned. They were an unlikely pair: Elara, with her gentle demeanor and dirt-stained gloves; Jax, with his stoic silence and eyes that had seen too much. But their combined expertise was unparalleled.', order: 1 },
        { id: 'c2_2', title: 'Chapter 2: Whispers in the Leaves', content: 'The jungle was alive, not just with animals, but with something...else. Days into their trek, the air in Xylos grew heavy, thick with the scent of unknown blossoms and damp earth. The sunlight, when it pierced the dense canopy, dappled the forest floor in ethereal patterns. Strange, flute-like calls echoed through the trees, too melodic for any bird Elara knew.<br/><br/>One evening, as Jax set snares, Elara knelt by a colossal, glowing mushroom. It pulsed with a soft, inner light, and she swore she could hear faint whispers emanating from it – not words, but emotions: curiosity, caution, ancient wisdom. Jax, ever pragmatic, grumbled about "jungle fever," but even he couldn’t deny the unsettling sentience that seemed to permeate Xylos. The plants themselves seemed to watch them, their leaves subtly turning as they passed. The very path they trod felt less like a trail and more like a permitted passage.', order: 2 },
    ],
    genre: 'Fantasy',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.5,
    views: 18000,
    isTrending: true,
    category: 'Trending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    dataAihint: "lush jungle"
  },
  {
    id: '3',
    title: 'The Alchemist of Moonhaven',
    author: 'Seraphina Gold',
    authorId: 'author3',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Moonhaven',
    description: 'In a city powered by moonlight, a young alchemist seeks a forbidden truth.',
    tags: ['steampunk', 'mystery', 'alchemy'],
    chapters: [{ id: 'c3_1', title: 'First Transmutation', content: 'The first attempt was a disaster, turning lead into... slightly shinier lead. Lyra sighed, wiping soot from her brow. Her small workshop, tucked away in the underbelly of Moonhaven, was a chaotic symphony of bubbling concoctions and ticking clockwork devices. Moonhaven itself was a marvel of gears and gaslight, its structures reaching towards the perpetually luminous moon, whose ethereal glow powered everything from the streetlamps to the grand Orrery at the city\'s heart. But Lyra sought a different kind of power, the ancient art of alchemy, an art the city\'s Mechanists\' Guild deemed obsolete and dangerous. Tonight, she was attempting the Magnum Opus, the creation of the Philosopher\'s Stone. So far, only her workbench was philosophically questioning its existence.', order: 1 }],
    genre: 'Steampunk',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.2,
    views: 12000,
    isCurated: true,
    category: 'Novel',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    dataAihint: "mystical city"
  },
  {
    id: '4',
    title: 'Echoes of the Void',
    author: 'Orion Nebula',
    authorId: 'author4',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Void',
    description: 'A lone astronaut confronts an ancient cosmic entity at the edge of known space.',
    tags: ['space opera', 'horror', 'existential'],
    chapters: [{ id: 'c4_1', title: 'The Signal', content: 'The long-range sensors of the ISV Serenity picked up an anomaly unlike anything ever recorded – a perfectly rhythmic pulse emanating from the Boötes Void, a sector of space so empty it was thought to be a cosmic error. Commander Eva Rostova, on the final leg of a five-year survey mission, was the only human within a dozen light-years. Against protocol, driven by a loneliness that gnawed deeper than the void itself, she altered course. The pulse was a song, a siren call in the silent emptiness, and Eva, despite her training, was compelled to listen.', order: 1 }],
    genre: 'Space Opera',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.9,
    views: 35000,
    isTrending: true,
    isCurated: true,
    category: 'SciFi',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    dataAihint: "galaxy stars"
  },
   {
    id: '5',
    title: 'The Last Cyberpunk',
    author: 'Nova Byte',
    authorId: 'user002', // Changed to AuthorAlex for profile page demo
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Cyber',
    description: 'In a neon-drenched city, one hacker fights for freedom.',
    tags: ['cyberpunk', 'dystopian', 'action'],
    chapters: [{ id: 'c5_1', title: 'The Glitch', content: 'The neon signs of Neo-Kyoto flickered, casting long, distorted shadows. A new directive flashed across Kiera "Glitch" Tanaka\'s retinal display: "Citizen #8086, report for Neural Optimization." She scoffed. "Optimization" was CorpSec euphemism for "mind-wipe." Not today. Not ever. Her fingers danced across her custom datapad, code scrolling faster than rain on a ferrocrete alley. It was time to remind the monolithic corporations that humanity wasn\'t just another programmable asset.', order: 1 }],
    genre: 'Cyberpunk',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.6,
    views: 22000,
    isTrending: true,
    category: 'SciFi',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 0).toISOString(),
    dataAihint: "neon city"
  },
  {
    id: '6',
    title: 'A Stitch in Time',
    author: 'Penelope Weave',
    authorId: 'author6',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Stitch',
    description: 'A short story about a magical tailor who can mend fate.',
    tags: ['short story', 'urban fantasy', 'magic'],
    chapters: [{ id: 'c6_1', title: 'The Golden Thread', content: 'The needle in Madam Evangeline’s hand hummed with ancient power, the thread itself shimmering with all the possibilities of a life yet unlived. Her clients didn’t come for new clothes; they came for new destinies. A snip here, a tuck there, and a disastrous romance could become a lifelong partnership, a failed business could find sudden fortune. But every stitch had its price, a truth young Finnigan was about to learn when he stumbled into her shop seeking to mend his broken heart.', order: 1 }],
    genre: 'Fantasy',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.3,
    views: 9000,
    category: 'ShortStory',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    dataAihint: "magic thread"
  },
  {
    id: '7',
    title: 'The Clockwork Heart',
    author: 'Cogsworth Tinkerton',
    authorId: 'author7',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Clockwork',
    description: 'A short tale of love and machinery in a Victorian-inspired world.',
    tags: ['short story', 'steampunk', 'romance'],
    chapters: [{ id: 'c7_1', title: 'The Unveiling', content: 'The automaton, designated Unit 7, stood gleaming under the gaslights of Professor Alistair Finch’s laboratory. Its heart, a marvel of intricate gears and shimmering aetheric crystals, ticked with a rhythm far too human for mere machinery. When Clara, the Professor’s bright, inquisitive daughter, first laid eyes on Unit 7, she saw not a machine, but a kindred spirit. But in a world wary of such creations, could a clockwork heart truly learn to love, and could society ever accept it?', order: 1 }],
    genre: 'Steampunk',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.7,
    views: 15000,
    category: 'ShortStory',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    dataAihint: "gears heart"
  },
   {
    id: '8',
    title: 'Love in the Time of Stardust',
    author: 'Stella Astra',
    authorId: 'author8',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Stardust',
    description: 'Two star-crossed lovers find each other across galaxies, their romance defying empires.',
    tags: ['romance', 'space opera', 'adventure'],
    chapters: [{ id: 'c8_1', title: 'Cosmic Encounter', content: 'Their ships nearly collided in the chaotic asteroid belt of the Cygnus-X1 nebula – Lyra, a rogue trader with a price on her head, and Orion, a stoic enforcer for the Galactic Hegemony. An accident that sparked an interstellar romance, a love that would challenge empires and rewrite star charts. But with the Hegemony hunting Lyra, and Orion torn between duty and desire, their stardust-crossed love seemed destined for tragedy, or perhaps, a revolution.', order: 1 }],
    genre: 'Romance',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.9,
    views: 28000,
    isTrending: true,
    category: 'Romance',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    dataAihint: "galaxy love"
  },
  {
    id: '9',
    title: 'The Secret Garden of Andromeda',
    author: 'Flora Nova',
    authorId: 'author9',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Andromeda',
    description: 'A botanist on a distant planet discovers a garden with plants that hold the universe\'s secrets.',
    tags: ['sci-fi', 'mystery', 'nature'],
    chapters: [{ id: 'c9_1', title: 'The Seedling', content: 'The deep space probe, "Pathfinder V," returned from the Andromeda galaxy with a single, impossible sample: a desiccated seed emitting faint, rhythmic energy pulses. Dr. Aris Thorne, xenobotanist aboard the orbital station Kepler, was tasked with coaxing it to life. Under the simulated sunlight of his zero-g biodome, the seed sprouted, revealing a plant that defied all known biology, its leaves shimmering with captured starlight and its roots humming with a silent song that seemed to whisper the secrets of the cosmos.', order: 1 }],
    genre: 'Science Fiction',
    status: 'Draft',
    publishedStatus: 'Draft',
    rating: 4.4,
    views: 5000,
    category: 'SciFi',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    dataAihint: "alien plants"
  },
  {
    id: '10',
    title: 'General Thoughts on Reading',
    author: 'Marcus Stone',
    authorId: 'author2',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=General',
    description: 'A general story for the general category, discussing the joys of reading any type of book.',
    tags: ['general', 'reading', 'books'],
    chapters: [{ id: 'c10_1', title: 'The Joy of Discovery', content: 'There is a unique magic in opening a book, whether it\'s a well-worn paperback or a crisp new hardcover. Each page holds the potential for a new world, a new friend, a new idea. It doesn\'t matter if it\'s dragons or spaceships, detectives or lovers; the act of reading itself is an adventure.', order: 1 }],
    genre: 'General',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.0,
    views: 3000,
    category: 'General',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 150).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 100).toISOString(),
    dataAihint: "books library"
  }
];

const mockPostComments: PostComment[] = [
  { id: 'comment1', postId: 'post1', userId: 'user001', username: 'ReaderRiley', avatarUrl: 'https://placehold.co/40x40/8E7CC3/FFFFFF?text=RR', text: "Great point!", timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), dataAihint: "user avatar", likes: 5, replies: [] },
  { id: 'comment2', postId: 'post1', userId: 'user002', username: 'AuthorAlex', avatarUrl: 'https://placehold.co/40x40/E8A87C/FFFFFF?text=AA', text: "I agree completely.", timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(), dataAihint: "user avatar", likes: 3, replies: [] },
  { id: 'comment3', postId: 'post2', userId: 'user001', username: 'ReaderRiley', avatarUrl: 'https://placehold.co/40x40/8E7CC3/FFFFFF?text=RR', text: "Interesting thought!", timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(), dataAihint: "user avatar", likes: 2, replies: [] },
  { id: 'comment4', postId: 'post3', userId: 'user123', username: 'StorySeeker92', avatarUrl: 'https://placehold.co/40x40/B4317B/F7F2FA?text=SS', text: "Rainy days are the best for reading!", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(), dataAihint: "user initial", likes: 10, replies: [] },
];

export const mockUserPosts: UserPost[] = [
  {
    id: 'post1',
    userId: 'user123',
    username: 'StorySeeker92',
    avatarUrl: 'https://placehold.co/40x40/B4317B/F7F2FA?text=SS',
    dataAihint: 'user initial',
    content: "Just finished reading 'The Whispers of Chronos' and my mind is blown! The ending was incredible. Has anyone else read it? What were your theories?",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likes: 152,
    comments: mockPostComments.filter(c => c.postId === 'post1'),
    isTrending: true,
  },
  {
    id: 'post2',
    userId: 'user123',
    username: 'StorySeeker92',
    avatarUrl: 'https://placehold.co/40x40/B4317B/F7F2FA?text=SS',
    dataAihint: 'user initial',
    content: "Looking for recommendations for a good space opera. Something with epic battles and cool alien races. Any suggestions from the Katha Vault community?",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    likes: 78,
    comments: mockPostComments.filter(c => c.postId === 'post2'),
  },
  {
    id: 'post3',
    userId: 'user001',
    username: 'ReaderRiley',
    avatarUrl: 'https://placehold.co/40x40/8E7CC3/FFFFFF?text=RR',
    dataAihint: 'user avatar',
    content: "What's everyone's favorite genre to read on a rainy day? For me, it's definitely a cozy mystery novel. ☕📚",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    likes: 205,
    comments: mockPostComments.filter(c => c.postId === 'post3'),
    isTrending: true,
  },
  {
    id: 'post4',
    userId: 'user002',
    username: 'AuthorAlex',
    avatarUrl: 'https://placehold.co/40x40/E8A87C/FFFFFF?text=AA',
    dataAihint: 'user avatar',
    content: "Working on a new chapter for my steampunk adventure! It's so exciting to see the world come to life. #WritingCommunity #Steampunk",
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    likes: 95,
    comments: [],
  },
];
