
import type { Story } from '@/types';

export const mockStories: Story[] = [
  {
    id: '1',
    title: 'The Whispers of Chronos',
    author: 'Eleanor Vance',
    authorId: 'author1',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Chronos', 
    description: 'A thrilling journey through time as a historian uncovers a device that can alter history.',
    tags: ['sci-fi', 'time travel', 'adventure'],
    chapters: [
        { id: 'c1_1', title: 'Chapter 1: The Attic Anomaly', content: 'The old grandfather clock in the attic wasn\'t just telling time; it was leaking it...', order: 1 },
        { id: 'c1_2', title: 'Chapter 2: Echoes of Tomorrow', content: 'His first jump was unintentional, a chaotic tumble into a future he barely recognized...', order: 2 },
        { id: 'c1_3', title: 'Chapter 3: The Chronos Protocol', content: 'The organization known only as "Veridian" had been tracking temporal disturbances...', order: 3 },
    ],
    genre: 'Science Fiction',
    status: 'Completed', // Narrative status
    publishedStatus: 'Published', // Publication status
    rating: 4.8,
    views: 25000,
    isTrending: true,
    isCurated: true,
    category: 'Trending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    dataAihint: "futuristic city"
  },
  {
    id: '2',
    title: 'Beneath the Emerald Canopy',
    author: 'Marcus Stone',
    authorId: 'author2',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Canopy',
    description: 'Explorers venture deep into an uncharted jungle, finding more than just exotic flora and fauna.',
    tags: ['fantasy', 'exploration', 'magic'],
    chapters: [
        { id: 'c2_1', title: 'Chapter 1: The Summons', content: 'The Royal Cartographers Guild had a new assignment...', order: 1 },
        { id: 'c2_2', title: 'Chapter 2: Whispers in the Leaves', content: 'The jungle was alive, not just with animals, but with something...else.', order: 2 },
    ],
    genre: 'Fantasy',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.5,
    views: 18000,
    isTrending: true,
    category: 'Trending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    dataAihint: "lush jungle"
  },
  {
    id: '3',
    title: 'The Alchemist of Moonhaven',
    author: 'Seraphina Gold',
    authorId: 'author3',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Moonhaven',
    description: 'In a city powered by moonlight, a young alchemist seeks a forbidden truth.',
    tags: ['steampunk', 'mystery', 'alchemy'],
    chapters: [{ id: 'c3_1', title: 'First Transmutation', content: '...', order: 1 }],
    genre: 'Steampunk',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.2,
    views: 12000,
    isCurated: true,
    category: 'Novel',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    dataAihint: "mystical city"
  },
  {
    id: '4',
    title: 'Echoes of the Void (Draft)',
    author: 'Orion Nebula',
    authorId: 'author4',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=VoidDraft',
    description: 'A lone astronaut confronts an ancient cosmic entity at the edge of known space. (Currently in Draft)',
    tags: ['space opera', 'horror', 'existential'],
    chapters: [{ id: 'c4_1', title: 'The Signal', content: '...', order: 1 }],
    genre: 'Space Opera',
    status: 'Ongoing',
    publishedStatus: 'Draft', // This story is a draft
    rating: 4.9,
    views: 35000,
    isTrending: false, 
    isCurated: true,
    category: 'SciFi',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    dataAihint: "galaxy stars"
  },
  {
    id: '5',
    title: 'The Last Cyberpunk',
    author: 'Nova Byte',
    authorId: 'author5',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Cyber',
    description: 'In a neon-drenched city, one hacker fights for freedom.',
    tags: ['cyberpunk', 'dystopian', 'action'],
    chapters: [{ id: 'c5_1', title: 'The Glitch', content: '...', order: 1 }],
    genre: 'Cyberpunk',
    status: 'Ongoing',
    publishedStatus: 'Published',
    rating: 4.6,
    views: 22000,
    isTrending: true,
    category: 'Trending',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date().toISOString(),
    dataAihint: "neon city"
  },
  {
    id: '6',
    title: 'A Stitch in Time',
    author: 'Penelope Weave',
    authorId: 'author6',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Stitch',
    description: 'A short story about a magical tailor who can mend fate.',
    tags: ['short story', 'urban fantasy', 'magic'],
    chapters: [{ id: 'c6_1', title: 'The Golden Thread', content: '...', order: 1 }],
    genre: 'Fantasy',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.3,
    views: 9000,
    category: 'ShortStory',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    dataAihint: "magic thread"
  },
   {
    id: '7',
    title: 'The Clockwork Heart',
    author: 'Cogsworth Tinkerton',
    authorId: 'author7',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Clockwork',
    description: 'A short tale of love and machinery in a Victorian-inspired world.',
    tags: ['short story', 'steampunk', 'romance'],
    chapters: [{ id: 'c7_1', title: 'The Unveiling', content: '...', order: 1 }],
    genre: 'Steampunk',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.7,
    views: 15000,
    category: 'ShortStory',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    dataAihint: "gears heart"
  },
  {
    id: '8',
    title: 'Love in the Lavender Fields',
    author: 'Flora Bloom',
    authorId: 'author8',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Love',
    description: 'A heartwarming romance blooms amidst picturesque lavender fields.',
    tags: ['romance', 'contemporary', 'heartwarming'],
    chapters: [{ id: 'c8_1', title: 'The Chance Encounter', content: '...', order: 1 }],
    genre: 'Romance',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.9,
    views: 32000,
    category: 'Romance',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    dataAihint: "lavender field"
  },
  {
    id: '9',
    title: 'Stars Beyond Reach (Review)',
    author: 'Astro Explorer',
    authorId: 'author9',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=StarsReview',
    description: 'A gripping sci-fi novel about humanity\'s first interstellar journey. (Awaiting Review)',
    tags: ['sci-fi', 'space exploration', 'adventure'],
    chapters: [{ id: 'c9_1', title: 'Launch Day', content: '...', order: 1 }],
    genre: 'Science Fiction',
    status: 'Ongoing',
    publishedStatus: 'Review', // This story is under review
    rating: 4.7,
    views: 28000,
    category: 'SciFi', 
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    dataAihint: "distant planet"
  },
  {
    id: '10',
    title: 'Secrets of the Silk Kimono',
    author: 'Yuki Tanaka',
    authorId: 'author10',
    coverImage: 'https://placehold.co/300x450/E62E9A/FFFFFF?text=Kimono',
    description: 'A forbidden love story set in feudal Japan, woven with mystery and tradition.',
    tags: ['romance', 'historical', 'mystery'],
    chapters: [{ id: 'c10_1', title: 'The Cherry Blossom Festival', content: '...', order: 1 }],
    genre: 'Romance',
    status: 'Completed',
    publishedStatus: 'Published',
    rating: 4.6,
    views: 19500,
    category: 'Romance',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    dataAihint: "japanese temple"
  },
];
